### Create New User Account

POST http://www.eventhive.local/api/auth/signup
Content-Type: application/json

{
    "username": "isira_adithya",
    "firstname": "Isira",
    "lastname": "Adithya",
    "email": "me@isiraadithya.com",
    "phone": "123456789",
    "address": "No 123, Sample Road, Test City",
    "password": "SuperSecurePass123",
    "role": "VISITOR"
}

### Create New EventOwner Account

POST http://www.eventhive.local/api/auth/signup
Content-Type: application/json

{
    "username": "isira_adithya_eo",
    "firstname": "Isira",
    "lastname": "Adithya (EventOwner)",
    "email": "eo@isiraadithya.com",
    "phone": "123456780",
    "address": "No 123, Sample Road, Test City",
    "password": "SuperSecurePass123",
    "role": "EVENT_OWNER"
}

### Login

POST http://www.eventhive.local/api/auth/login
Content-Type: application/json

{
    "username": "isira_adithya",
    "password": "SuperSecurePass123"
}

### Login EO

POST http://www.eventhive.local/api/auth/login
Content-Type: application/json

{
    "username": "isira_adithya_eo",
    "password": "SuperSecurePass123"
}

### Logout

DELETE  http://www.eventhive.local/api/auth/logout
Content-Type: application/json
Cookie: connect.sid=s%3AP0ODPxXW4oVS8yJ4GR-SGvu9v5mw304q.uJQVuNs8TbA4MV5vlUjwVF5f4NC4loCKipvRPJahCNg;

{
    "username": "isira_adithya",
    "password": "SuperSecurePass123"
}

### Request a Password Reset Token

POST  http://www.eventhive.local/api/auth/reset-password/request
Content-Type: application/json

{
    "username": "isira_adithya"
}

### Reset Password using token

POST  http://www.eventhive.local/api/auth/reset-password/reset
Content-Type: application/json

{
    "token": "895ccb1c399430eda115ff38a7f0b029ba6e210078dcbeeeec0fd1f8af1349c7",
    "newPassword": "HelloWorld"
}